version: '3'

services:
  publications:
    image: ghcr.io/ghosts-network/publications:latest
    ports:
      - "5300:80"
    depends_on:
      - db
    environment:
      - MONGO_CONNECTION=mongodb://db:27017/gpublications
      - ASPNETCORE_ENVIRONMENT=Development

  profiles:
    image: ghcr.io/ghosts-network/profiles:latest
    ports:
      - "5400:80"
    depends_on:
      - db
    environment:
      - MONGO_CONNECTION=mongodb://db:27017/gprofiles
      - ASPNETCORE_ENVIRONMENT=Development

  db:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"

  gateway:
    image: ghcr.io/ghosts-network/gateway:latest
    ports:
      - "5000:80"
    depends_on:
      - publications
      - reactions
      - profiles
      - account
    environment:
      - PUBLICATIONS_ADDRESS=http://publications
      - PROFILES_ADDRESS=http://profiles
      - ASPNETCORE_ENVIRONMENT=Development
